# Python package

# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool:
  vmImage: ubuntu-latest
strategy:
  matrix:
    #Python27:
      #python.version: '2.7'
    Python37:
      python.version: '3.7'

variables:
- group: testgithubtok

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    pip install pytest pytest-azurepipelines
    pytest
  displayName: 'pytest'

- script: |
    echo $(Gtokn)

- task: PublishPipelineArtifact@1
  inputs:
    pathToPublish: '$(System.DefaultWorkingDirectory)/bin'
    artifactName: 'OmArtifact'

#- task: CmdLine@2
 # inputs:
  #  script: |
   #   # Configure git
    #  git config --global user.email "sudhirnaswa@gmail.com"
     # git config --global user.name "snaswa"
      
      # Add the artifact to the repository
      #git add .
      
      # Commit the changes
      #git commit -m "Add artifact"
      
      # Push the changes to the repository
     # git push origin HEAD:main
  #env:
    # Set the GitHub personal access token as an environment variable
    #GITHUB_TOKEN: $(GITHUB_TOKEN)
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'